var GAME_LEVELS = [
  ["                                                                                            ",
   "                                                                 o                          ",
   "                                                  oo                                        ",
   "                                                  oo          o  o  o                       ",
   "                                            oooo       oo       o                           ",
   "                                            yyyy   m   yyy    o                             ",
   "                               o         oooy     yyy         m      o                      ",
   "                               y      oooyyyy                 yy    yy                      ",
   "                               y o    yyyy                     y!!!!y                       ",
   "                               yyy                             yy!!yy      m                ",
   "                                                                yyyy      xxxx              ",
   "                                                                             x              ",
   "  xx                    o                 o o                          y     x              ",
   "  x                     o           yy     m         xx            xx        x              ",
   "  x            x        o        x        yyyy      xx             xx      o x              ",
   "  x          xxx       yy       xx                 xxx            xxx        x       xx     ",
   "  x          x    yy           xx        m        xxxx         xxxxxxx       x      xxxx  x ",
   "  x  @   m   x              xxxx       xxxxxxxxxxxxxxx!!!!!!xxxxxxxxx    xxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxxx!!!!!!!!!!!!!!xxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!xxx               ",
   "  xxxxxxxxxxxx!!!!!!!!!!!!!xxxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!xxx               ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!xxx               ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                                                            ",
   "                                                                                            "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                 x                             xx    x                             x         x                    ",
   "                 x                             x     x      o  o     x   x         x         x                    ",
   "                 xxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "    @                xx         x     x        x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "xxxxxxx               xx        x o   x        x    xx               x   x   x               x                    ",
   "xxxxxxx                x        x     x        x     x               x   x   x               x                    ",
   "xxxxxxx      x         x        x  y  x        x     x               x   xxxxx   xxxxxx      x                    ",
   "xxxxxxx      x         x!!!!!!!x      x        x     x               x     o     x x         x                    ",
   "xxxxxxx!!!!!!x         x!!v!!!xx      x!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "xxxxxxx!!!!!!x         xxx xxxxx  y   xxxxxxxxxx!!!!!x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "xxxxxxx!!!!!!x                         xx!!!!!!!!!!!xx!!!!!!xx !                    xx     xx                     ",
   "xxxxxxx!!!!!!x                         xx!!!!!!!!!!xx!!!!!!xx  !                     xxxxxxx                      ",
   "xxxxxxx!!!!!!x                       xxxxxxxxxxxxxxx!!!!!xx    !                                                  ",
   "xxxxxxx!!!!!!x                 xxxxxxxxxxxxxxxxxxxxx!!!!!xx    !                                                  ",
   "xxxxxxx!!!!!!x              xxxxxxxxxxxxxxxxxxxxxxxx!!!!!xx    !                                                  ",
   "xxxxxxx!!!!!!x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xx    !                                                  ",
   "xxxxxxx!!!!!!x   yy    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xx    !                                                  ",
   "xxxxxxx!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
